version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "automerge"
    ignore:
      - update-types:
          - "version-update:semver-major"